# fly.toml app configuration file generated for evanoconnor-ie on 2024-03-29T00:19:09Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "evanoconnor-ie"
primary_region = "cdg"

[http_service]
  auto_start_machines = true
  auto_stop_machines = "stop"
  force_https = true
  internal_port = 80
  min_machines_running = 1
  processes = ["app"]

[http_service.http_options.response]
  pristine = true

[[http_service.checks]]
  grace_period = "30s"
  interval = "1m"
  method = "GET"
  path = "/"
  timeout = "5s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"
