# fly.toml app configuration file generated for evanoconnor-ie on 2024-03-29T00:19:09Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "evanoconnor-ie"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[deploy]
  strategy = "canary"

[http_service]
  auto_start_machines = true
  auto_stop_machines = "stop"
  force_https = true
  internal_port = 80
  min_machines_running = 1
  http_options.response.pristine = true

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "256mb"
