name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: macos-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout Git repo
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
    
      - name: Install dependencies
        run: npm ci --include=dev --force
      
      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
        env:
          DOTENV_PRIVATE_KEY_PRODUCTION: ${{ secrets.DOTENV_PRIVATE_KEY_PRODUCTION }}

      - name: Cache build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: standalone
          path: .next/standalone
