name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: macos-latest
    concurrency: deploy-group
    steps:
      - name: Checkout Git repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
   
      - name: Install dependencies
        run: npm ci --include=dev

      - name: Deploy
        run: npm run deploy:fly
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          DOTENV_PRIVATE_KEY_PRODUCTION: ${{ secrets.DOTENV_PRIVATE_KEY_PRODUCTION }}
